package machine

enum class CoffeeMachineMaterialsNeed(val amount: Int) {
    ESPRESSO_WATER_NEED(250),
    ESPRESSO_COFFEE_BEANS_NEED(16),
    LATTE_WATER_NEED(350),
    LATTE_MILK_NEED(75),
    LATTE_COFFEE_BEANS_NEED(20),
    CAPPUCCINO_WATER_NEED(200),
    CAPPUCCINO_MILK_NEED(100),
    CAPPUCCINO_COFFEE_BEANS_NEED(12)
}